//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductsAPI.APIConstants", typeof(APIConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-API-VERSION.
        /// </summary>
        internal static string API_VERSION_HEADER {
            get {
                return ResourceManager.GetString("API_VERSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string API_VERSION_VALUE {
            get {
                return ResourceManager.GetString("API_VERSION_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aspmvcsignalrtest.azurewebsites.net/.
        /// </summary>
        internal static string DEFAULT_URL_SERVER {
            get {
                return ResourceManager.GetString("DEFAULT_URL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/account.
        /// </summary>
        internal static string URL_ACCOUNTS {
            get {
                return ResourceManager.GetString("URL_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/{0}/create.
        /// </summary>
        internal static string URL_CREATE_PRODUCT_ENTRY {
            get {
                return ResourceManager.GetString("URL_CREATE_PRODUCT_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/create.
        /// </summary>
        internal static string URL_CREATE_PRODUCT_LIST {
            get {
                return ResourceManager.GetString("URL_CREATE_PRODUCT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/{0}/delete/{1}.
        /// </summary>
        internal static string URL_DELETE_PRODUCT_ENTRY {
            get {
                return ResourceManager.GetString("URL_DELETE_PRODUCT_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/delete/{0}.
        /// </summary>
        internal static string URL_DELETE_PRODUCT_LIST {
            get {
                return ResourceManager.GetString("URL_DELETE_PRODUCT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/{0}/edit/{1}.
        /// </summary>
        internal static string URL_EDIT_PRODUCT_ENTRY {
            get {
                return ResourceManager.GetString("URL_EDIT_PRODUCT_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/account/login.
        /// </summary>
        internal static string URL_LOGIN_USER {
            get {
                return ResourceManager.GetString("URL_LOGIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/account/logout.
        /// </summary>
        internal static string URL_LOGOUT_USER {
            get {
                return ResourceManager.GetString("URL_LOGOUT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists/{0}.
        /// </summary>
        internal static string URL_PRODUCT_ENTRIES {
            get {
                return ResourceManager.GetString("URL_PRODUCT_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/productlists.
        /// </summary>
        internal static string URL_PRODUCT_LISTS {
            get {
                return ResourceManager.GetString("URL_PRODUCT_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/account/register.
        /// </summary>
        internal static string URL_REGISTER_USER {
            get {
                return ResourceManager.GetString("URL_REGISTER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /signalr.
        /// </summary>
        internal static string URL_SIGNALR_HUB {
            get {
                return ResourceManager.GetString("URL_SIGNALR_HUB", resourceCulture);
            }
        }
    }
}
